Help text cleanup
astronomer/astro-cli pull request #1234
Opened 2023-06-02 15:13 UTC by jwitz

Just a minor help text cleanup

2023-06-02 15:39 UTC, kushalmalani approved these changes

2023-06-07 15:35 UTC, sunkickr requested changes

2023-06-08 13:35 UTC, jwitz commented on cmd/airflow.go
> +	cmd.Flags().StringVarP(&composeFile, "compose-file", "", "", "Location of a custom Docker compose file to use for starting Airflow")
```suggestion
	cmd.Flags().StringVarP(&composeFile, "compose-file", "", "", "Location of a custom compose file to use for starting Airflow")
```

2023-06-09 16:30 UTC, sunkickr approved these changes

2023-06-09 16:30 UTC, merged