add flag --runtime-version to dev init command
astronomer/astro-cli pull request #533
Opened 2022-04-27 11:04 UTC by AmFlint

## Description

We want to allow users to initialize a project with a specific runtime version. Before this PR, users could only provide an airflow version (with flag --airflow-version or -v) and we would find the latest release for runtime matching this airflow version.

In this PR, I added a flag --runtime-version that allows users to specify which runtime version they want to use. We check if the provided runtime version is a valid one, else we ignore and use the latest stable one.

## 🎟 Issue(s)

https://github.com/astronomer/issues/issues/4542

## 🧪 Functional Testing

Will be added to the linked issue.

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `make test` before taking out of draft
- [x] Added/updated applicable tests
- [x] Tested against [Houston-API](https://github.com/astronomer/houston-api/) and [Astronomer](https://github.com/astronomer/astronomer/) (if necessary).
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

2022-04-27 12:39 UTC, andriisoldatenko approved these changes

2022-04-27 12:40 UTC, andriisoldatenko commented
@AmFlint could you please add test.

2022-04-27 17:04 UTC, neel-astro approved these changes
looks fine 👍

2022-04-28 08:20 UTC, AmFlint commented
> @AmFlint could you please add test.

Where do you want me to add tests ? I added tests to every place I updated except the actual command itself which is going to be tested in an e2e manner probably in the QA testing repository ?

2022-04-28 08:29 UTC, andriisoldatenko requested changes

2022-04-28 08:29 UTC, andriisoldatenko commented on cmd/airflow.go
> +	// if runtime version is set, use runtime version. If user specifies --use-astronomer-certified, or use runtime but didn't provide version, get default image tag
@AmFlint if you run go test with coverage you can see in html report:

```
go tool cover -html=cover.out
go test -coverprofile cover.out -v -tags=containers_image_openpgp,exclude_graphdriver_btrfs,exclude_graphdriver_devicemapper ./...
```

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/1374633/165711112-3bbb7ceb-e427-42a2-8cbd-a17124dc22b2.png">

2022-04-29 15:53 UTC, andriisoldatenko approved these changes

2022-04-29 18:42 UTC, merged